config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

     resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	#new Projects
	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			flash[:notice] = "project has been creaated"
			redirect_to @project
		else
			#nothing , yet
		end
	end

	def show
		@project = Project.find(params[:id])
	end

	def index
		@projects = Project.first(3)
	end

	private
	def project_params
		params.require(:project).permit(:name, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ticketee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
	<div class='flash' id='<%= key %>'>
		<%= value %>
	</div>
<% end %>

<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>

app/views/projects/new.html.erb
new project

<%= form_for @project do |f| %>
  <p>
  	<%= f.label :name , "Your name" %>
  	<%= f.text_field :name %>
  </p>
  <p>
	<%= f.label :description, "description about project" %>
  	<%= f.text_field :description %>
  </p>
  <%= f.submit "Submit", :disable_with => 'Submiting...' %>
<% end %>

app/views/projects/show.html.erb
showing

<h2> <%= @project.name %>